### ISSUE TITLE
Cooperatively working with "async-recursion" crate

### ISSUE THREAD

**Issue by Tarbetu** [DelSkayn/reblessive#1]
Hi!

I like this project, however I have to say that requirement for "async" also brings the need for [async-recursion](https://crates.io/crates/async_recursion) crate because the recursion in async functions are forbidden by the compiler.

"Ctx" also needs a lifetime declaration, and it complicates the situations with this crate.

You might provide more documentation for possibly pitfalls and caveats while using "async-recursion"

Thank you.

**Comment by DelSkayn** [comment]
It does indeed currently require async-recursion crate but in the upcoming beta version 1.77 the restriction which forces you to use async-recursion will be lifted. So [this PR.](https://github.com/rust-lang/rust/pull/117703)

I had locally already changed the minimal supported rust version to 1.77 but I see I haven't yet pushed that change. 

Note that this is still a very much in development library so expect some cruft here and there.
